### ISSUE TITLE
Make kanban board Template

### ISSUE THREAD

**Issue by zunairkhan811** [zunairkhan811/Ruby-Catalog-Project#26]
- We are three team members in this Ruby-Catalog-Project
      - Team Member#1: Muhammad Zunair khan (@zunairkhan811)
      - Team Member#2: Lawrence Amoafo (@Kwaku28)
      - Team Member#3: Roland Ntwali (@Roland-Ntwali)
- [Project Link](https://github.com/users/zunairkhan811/projects/3)

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
